import Link from 'next/link'
import './globals.css'
import Head from 'next/head'


export const metadata = {
  title: 'Mobile Recharge - Hoogaaa',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
    <Link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-grid/4.0.6/ui-grid.css" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-grid/4.0.6/ui-grid.min.js"/>
    </Head>
      <body>{children}</body>
    </html>
  )
}
